### PR TITLE
[Team member #3- Author-Game classes]Ruby Capstone Project

### LINKED ISSUE #8: [1pt]Create a Game class in a separate .rb file.
-  Create a Game class in a separate .rb file.
- All Game class properties visible in the diagram should be defined and set up in the constructor method.

### LINKED ISSUE #9: [0.5pt]Create an Author class with an association with the Item class
- Create an Author class with an association to the Item class (in a separate .rb file).

- All Author class properties visible in the diagram should be defined and set up in the constructor method.

### LINKED ISSUE #11: [1pt] - Implements methods
Implement methods:

add_item method in the Author class

should take an instance of the Item class as an input
should add the input item to the collection of items
should add self as a property of the item object (by using the correct setter from the item object)
can_be_archived?() in the Game class
should override the method from the parent class
should return true if parent's method returns true AND if last_played_at is older than 2 years
otherwise, it should return false

### LINKED ISSUE #14: [1.5pt]Add unit tests for all implemented methods.
Add unit tests for all implemented methods.

### LINKED ISSUE #15: [1pt] Addgame,List game, List Athor
The following options should be available:
List of games
List all authors (e.g. 'Stephen King')
Add a game

### LINKED ISSUE #16: [1pt]Preserved Data
All data should be preserved by saving collections in .json files.

### LINKED ISSUE #18: [1pt]Create a schema.sql file with tables
Create a schema.sql file with tables that will be analogical to the structure of the classes that you created:
games table (add all properties and associations from the parent Item class as table columns)
authors table

### PR DESCRIPTION
**Pull request by binodbhusal**
**Team member #3** 

- [x] Create a Game class in a separate .rb file.

- [x] Create an Author class with an association to the Item class (in a separate .rb file).

- [x] All Game class properties visible in the diagram should be defined and set up in the constructor method.

- [x] All Author class properties visible in the diagram should be defined and set up in the constructor method.

 

- [x] **Implement methods:**

- [x] add_item method in the Author class
- [x] should take an instance of the Item class as an input
- [x] should add the input item to the collection of items
- [x] should add self as a property of the item object (by using the correct setter from the item 
- [x]                    object)
- [x] can_be_archived?() in the Game class
- [x] should override the method from the parent class
- [x] should return true if parent's method returns true AND if last_played_at is older than 2 years
 otherwise, it should return false

- [x] Add unit tests for all implemented methods.

- [x] **The following options should be available:**

- [x] List of games
- [x] List all authors (e.g. 'Stephen King')
- [x] Add a game

- [x] All data should be preserved by saving collections in .json files.

- [x] Create a schema.sql file with tables that will be analogical to the structure of the classes that you created:

- [x] games table (add all properties and associations from the parent Item class as table columns)

authors table

### CODE REVIEW

**Review by akezeth — APPROVED** [review]
STATUS: 🟢 APPROVED!!! 🎉 🎉 🎉
Good work on making the effort in this milestone.

Great job !!! 👏 👏 👏
Your project is complete!

Now you can move on 🥇
Congratulations! 🎉 🎉 🎉 🍾 🍾 🍾
To Highlight 🎉
No Linters errors ✔️
Created  Game and Author classes ✔️
The app works as expected ✅
Good commit messages. 👍

Optional suggestions ✍️
N/A
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Happy Coding! 👨‍💻 and Good Luck 🍀 with the coming ones 🤞
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @akezeth in your question so I can receive the notification, you can also reach me out on Slack using the same tag as well.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Review by HafizMassamTabraizKhan — APPROVED** [review]
STATUS: APPROVED! 🍾 🎆 🥇

You did a great job working on this capstone, your project is complete! 🚀
There is nothing else to say other than... it's time to merge it 🤖
Congratulations! 🎉
Now you can move on 🥇

To Highlight 🎉
No Linters errors ✔️
The app works as expected ✅
Good commit messages. 👍

Cheers, and Happy coding!👏👏👏

**Review by HafizMassamTabraizKhan — APPROVED** [review]
STATUS: 🟢 APPROVED!!! 🎉 🎉 🎉
Hi @binodbhusal ,
You did a great job working on this capstone, your project is complete! 🚀
There is nothing else to say other than... it's time to merge it 🤖

Now you can move on 🥇
Congratulations! 🎉 🎉 🎉 🍾 🍾 🍾
To Highlight 🎉
No Linters errors ✔️
Implemented required methods✔️
The app works as expected ✅
Good commit messages. 👍

Optional suggestions ✍️
N/A
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Happy Coding! 👨‍💻 and Good Luck 🍀 with the coming ones 🤞
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @binodbhusal in your question so I can receive the notification, you can also reach me out on Slack using the same tag as well.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Review by akezeth — APPROVED** [review]
STATUS: APPROVED! 🍾 🎆 🥇

You did a great job working on this capstone, your project is complete! 🚀
There is nothing else to say other than... it's time to merge it 🤖
Congratulations! 🎉
Now you can move on 🥇

To Highlight 🎉
No Linters errors ✔️
The app works as expected ✅
Good commit messages. 👍

Cheers, and Happy coding!👏👏👏

**Pull request merged**
